### ISSUE TITLE
Tracking issue for types/objects/concepts that should be renamed

### ISSUE THREAD

**Issue by ulysseB** [ulysseB/telamon#39]
Comment to propose types, objects or concepts that should be renamed or to propose new names for the names listed bellow.

In Telamon:
- `BasicBlock` => `Statement`
- `MemBlock` => `MemoryRegion`

In Telamon-gen
- `Action` could be renamed to `Decision`
- counter `value` => `incr_amount`
- `ir::CounterKind` => `ir::CounterOperator`

**Comment by Elarnon** [comment]
Possible alternatives:
 - `Statement` for `BasicBlock`
 - `MemoryRegion` or `MemRegion` for `MemBlock`
