### ISSUE TITLE
Allow executors to fail

### ISSUE THREAD

**Issue by Elarnon** [ulysseB/telamon#52]
Currently  the available executors are defined based on feature flags and the complete function/type definitions are erased when the feature is disabled.

It would be useful to keep a thin API layer for interoperability even when the feature is disabled, and to make it so that the API can fail. This would allow:

 - Writing generic code which dynamically checks for a feature (e.g. using `cfg!(feature)` instead of `#[cfg(feature)]` and #[cfg(not(feature))]` pairs).
 - In a second time, allow features to be compiled in and fail gracefully (i.e. without panicking) if no hardware accelerator is found on the current machine.

**Comment by ulysseB** [comment]
Now working on making the `device/cuda` module available without the `cuda` feature. The goal is to:
- isolate the part that relies on the cuda driver in the `device/cuda/api` module
- provide a fake implementation for submodule of `api` that depends on the cuda runtime
- fail when creating the executor
